#
# Module manifest for module 'SharedDscConfig'
#
# Generated by: Gael
#
# Generated on: 08/06/2017
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Shared2.schema.psm1'

# Version number of this module.
ModuleVersion = '0.0.1'

# ID used to uniquely identify this module
GUID = '1fb02696-de3d-4f86-8e83-3a65696edffd'

# Author of this module
Author = 'Gael Colas'

# Company or vendor of this module
CompanyName = 'SynEdgy Ltd'

# Copyright statement for this module
Copyright = '(c) 2017 Gael. All rights reserved.'

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @('PSDesiredStateConfiguration')

# DSC resources to export from this module
DscResourcesToExport = @('Shared2')

}

